import { Inter, Handjet } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { Toaster } from "@/components/ui/sonner";
import { List } from "phosphor-react";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Bruno de Almeida Aseff",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

const handjet = Handjet({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-handjet",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${handjet.variable}`}>
        <main className="h-screen relative flex flex-col items-center justify-between w-full   ">
          <Image
            priority
            alt="Background"
            src="/opcao_2.jpeg"
            quality={100}
            fill
            sizes="100vw"
            style={{
              objectFit: "cover",
            }}
          />

          <Navbar />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
