import { Inter, Handjet } from "next/font/google";
import "./globals.css";
import { AnimatePresence, motion } from "framer-motion";

export const metadata = {
  title: "Bruno de Almeida Aseff",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

const handjet = Handjet({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-handjet",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${handjet.variable}`}>
        {children}
      </body>
    </html>
  );
}
